# *** THIS FILE IS GENERATED - DO NOT EDIT ***
# See vksc_convert_tests.py for modifications

# ~~~
# Copyright (c) 2023-2023 RasterGrid Kft.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ~~~

set(VKSC_CONVERTED_TEST_FILES
    converted/amd_best_practices.cpp
    converted/android_external_resolve.cpp
    converted/android_external_resolve_positive.cpp
    converted/android_hardware_buffer.cpp
    converted/android_hardware_buffer_positive.cpp
    converted/arm_best_practices.cpp
    converted/atomics.cpp
    converted/atomics_positive.cpp
    converted/best_practices.cpp
    converted/best_practices_positive.cpp
    converted/buffer.cpp
    converted/buffer_positive.cpp
    converted/command.cpp
    converted/command_positive.cpp
    converted/copy_buffer_image.cpp
    converted/copy_buffer_image_positive.cpp
    converted/debug_extensions.cpp
    converted/debug_extensions_positive.cpp
    converted/debug_printf.cpp
    converted/descriptor_buffer.cpp
    converted/descriptor_buffer_positive.cpp
    converted/descriptor_indexing.cpp
    converted/descriptor_indexing_positive.cpp
    converted/descriptors.cpp
    converted/descriptors_positive.cpp
    converted/device_queue.cpp
    converted/dynamic_rendering.cpp
    converted/dynamic_rendering_local_read.cpp
    converted/dynamic_rendering_local_read_positive.cpp
    converted/dynamic_rendering_positive.cpp
    converted/dynamic_state.cpp
    converted/dynamic_state_positive.cpp
    converted/external_memory_sync.cpp
    converted/external_memory_sync_positive.cpp
    converted/fragment_shading_rate.cpp
    converted/fragment_shading_rate_positive.cpp
    converted/geometry_tessellation.cpp
    converted/geometry_tessellation_positive.cpp
    converted/gpu_av.cpp
    converted/gpu_av_buffer_device_address.cpp
    converted/gpu_av_buffer_device_address_positive.cpp
    converted/gpu_av_descriptor_indexing.cpp
    converted/gpu_av_descriptor_indexing_positive.cpp
    converted/gpu_av_indirect_buffer.cpp
    converted/gpu_av_oob.cpp
    converted/gpu_av_oob_positive.cpp
    converted/gpu_av_positive.cpp
    converted/gpu_av_ray_query.cpp
    converted/gpu_av_ray_query_positive.cpp
    converted/gpu_av_ray_tracing.cpp
    converted/gpu_av_ray_tracing_positive.cpp
    converted/gpu_av_shader_object_positive.cpp
    converted/gpu_av_spirv.cpp
    converted/gpu_av_spirv_positive.cpp
    converted/graphics_library.cpp
    converted/graphics_library_positive.cpp
    converted/host_image_copy.cpp
    converted/host_image_copy_positive.cpp
    converted/image.cpp
    converted/image_drm.cpp
    converted/image_drm_positive.cpp
    converted/image_positive.cpp
    converted/imageless_framebuffer.cpp
    converted/imageless_framebuffer_positive.cpp
    converted/instance_positive.cpp
    converted/instanceless.cpp
    converted/layer_utils_positive.cpp
    converted/memory.cpp
    converted/memory_positive.cpp
    converted/mesh.cpp
    converted/mesh_positive.cpp
    converted/multiview.cpp
    converted/nvidia_best_practices.cpp
    converted/object_lifetime.cpp
    converted/object_lifetime_positive.cpp
    converted/other_positive.cpp
    converted/others.cpp
    converted/parent.cpp
    converted/parent_positive.cpp
    converted/pipeline.cpp
    converted/pipeline_advanced_blend.cpp
    converted/pipeline_layout.cpp
    converted/pipeline_layout_positive.cpp
    converted/pipeline_positive.cpp
    converted/pipeline_topology.cpp
    converted/pipeline_topology_positive.cpp
    converted/portability_subset.cpp
    converted/protected_memory.cpp
    converted/protected_memory_positive.cpp
    converted/push_descriptor.cpp
    converted/push_descriptor_positive.cpp
    converted/query.cpp
    converted/query_positive.cpp
    converted/ray_tracing.cpp
    converted/ray_tracing_nv.cpp
    converted/ray_tracing_pipeline.cpp
    converted/ray_tracing_pipeline_nv.cpp
    converted/ray_tracing_pipeline_positive.cpp
    converted/ray_tracing_pipeline_positive_nv.cpp
    converted/ray_tracing_positive.cpp
    converted/render_pass.cpp
    converted/render_pass_positive.cpp
    converted/robustness.cpp
    converted/robustness_positive.cpp
    converted/sampler.cpp
    converted/sampler_positive.cpp
    converted/secondary_command_buffer.cpp
    converted/secondary_command_buffer_positive.cpp
    converted/shader_compute.cpp
    converted/shader_compute_positive.cpp
    converted/shader_cooperative_matrix.cpp
    converted/shader_cooperative_matrix_positive.cpp
    converted/shader_image_access.cpp
    converted/shader_image_access_positive.cpp
    converted/shader_interface.cpp
    converted/shader_interface_positive.cpp
    converted/shader_limits.cpp
    converted/shader_limits_positive.cpp
    converted/shader_mesh.cpp
    converted/shader_object.cpp
    converted/shader_object_positive.cpp
    converted/shader_push_constants.cpp
    converted/shader_push_constants_positive.cpp
    converted/shader_spirv.cpp
    converted/shader_spirv_positive.cpp
    converted/shader_storage_image.cpp
    converted/shader_storage_image_positive.cpp
    converted/shader_storage_texel.cpp
    converted/shader_storage_texel_positive.cpp
    converted/sparse_buffer.cpp
    converted/sparse_buffer_positive.cpp
    converted/sparse_image.cpp
    converted/sparse_image_positive.cpp
    converted/subgroups.cpp
    converted/subpass.cpp
    converted/subpass_positive.cpp
    converted/sync_object.cpp
    converted/sync_object_positive.cpp
    converted/sync_val.cpp
    converted/sync_val_positive.cpp
    converted/threading.cpp
    converted/threading_positive.cpp
    converted/tooling.cpp
    converted/tooling_positive.cpp
    converted/transform_feedback.cpp
    converted/vertex_input.cpp
    converted/vertex_input_positive.cpp
    converted/video.cpp
    converted/video_positive.cpp
    converted/viewport_inheritance.cpp
    converted/wsi.cpp
    converted/wsi_positive.cpp
    converted/ycbcr.cpp
    converted/ycbcr_positive.cpp
)
